### ISSUE TITLE
Null bytes not trimmed.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [andris9/encoding#14]
Please excuse me if this is the intended behavior but null bytes are not removed from end of the string.

Example code (it is Encoded correctly however the null bytes are there....)
```
console.log(encoding.convert('\xC7\xAE\xB1\xD2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00','UTF-8', 'EUC-CN').toString().length);
```

The word is 钱币 in English Coin.

A simple regex replace seems to handle it,However I am not sure if it is the correct solution.
```
string.replace(/\0\0.*/,'')
```

**Comment by andris9** [comment]
Why should the null bytes be removed? In JavaScript thats a valid character.

**Comment by LiamKarlMitchell** [comment]
Sure, I guess it is fine the way it is then, thanks.
It is just that in every other language I have seen null terminates a string.

**Comment by andris9** [comment]
Thats not the case in javascript, null bytes are just as fine string bytes than any other bytes
