### ISSUE TITLE
Warnings with webpack. 

### ISSUE THREAD

**Issue by hh9527** [andris9/encoding#16]
```
WARNING in d:/dws/projects/febs/febs/~/encoding/lib/encoding.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ d:/dws/projects/febs/febs/~/encoding/lib/encoding.js 9:12-34
```

Related code: https://github.com/andris9/encoding/blob/master/lib/encoding.js#L9

Please dont try to fool webpack, users can use webpack.IgnorePlugin to prevent loading of 'iconv'.

**Comment by andris9** [comment]
This module is meant for Node only, do not use it with webpack if it doesn't work

**Comment by hh9527** [comment]
I use this module **in node env**. With webpack, the server side application can be packaged in one js file with only required source files included.

**Comment by andris9** [comment]
This behavior with *require* as an expression is intentional to be able to load *iconv* in environments where it is supported and fall back to *iconv-lite* where it is not. Webpack support is not a priority.

**Comment by hh9527** [comment]
Currently, webpack is ok except the warnings.

But change these 2 lines
```js
    var iconv_package = 'iconv';
    Iconv = require(iconv_package).Iconv;
```

to

```js
    Iconv = require('iconv').Iconv;
```

will allow user to avoid the warning.

**Comment by andris9** [comment]
This change would break browserify which is more used than webpack. I'm willing to change the code to support webpack as well but only if it doesn't break anything existing.

**Comment by hh9527** [comment]
OK, thank you.

There is a way to do that:
```js
Iconv = require('./iconv-loader');
```

and

```js
// file: iconv-loader.js
var pkg = 'iconv';
module.exports = require(pkg);
```

and then, user can use webpack.IgnorePlugin to ignore `/\/iconv-loader$/`

**Comment by andris9** [comment]
Updated code to load Iconv as you suggested. Released as v0.1.12

**Comment by hh9527** [comment]
Thank you!

**Comment by silvenon** [comment]
Won't this cause an error as soon as it's run with Node? I get this:

```
Error: Cannot find module "./iconv-loader"
```

I think it's meant for `require`s which are inside a `try...catch` block?

**Comment by silvenon** [comment]
This works:

```js
  module: {
    exprContextRegExp: /$^/,
    exprContextCritical: false,
    loaders: [/*...*/]
  }
```

It invalidates all `require(expr)` cases, like this one (stolen from https://github.com/webpack/webpack/issues/198#issuecomment-37306725). It will throw on [`require(iconv_package)`](https://github.com/andris9/encoding/blob/91ae950aaa854a119122c27cdbabd8c5585106f7/lib/iconv-loader.js#L9) just as the Universe intended.

**Comment by jimpick** [comment]
IgnorePlugin didn't work for me, when I used it, webpack put in some code that throws an error. I did this instead in plugins:

new webpack.NormalModuleReplacementPlugin(/\/iconv-loader$/, 'node-noop')

I needed to install the node-noop npm module.

**Comment by silvenon** [comment]
@jimpick that's much cleaner, thanks :+1:

**Comment by yinfxs** [comment]
Use the 'whatwg-fetch' instead of 'node-fetch'

**Comment by silvenon** [comment]
whatwg-fetch does not work in Node. This issue is probably most common when you're trying to compile your tests with webpack before running them, so you have good control over how some special stuff like CSS imports will be handled.

Eventually I realized that doing that is an overkill and I can just use `require.extensions` to nullify those imports.

**Comment by rublev** [comment]
@silvenon 

>Eventually I realized that doing that is an overkill and I can just use require.extensions to nullify those imports.

How?

**Comment by Artexoid** [comment]
https://github.com/kadirahq/lokka-transport-http/issues/22

**Comment by silvenon** [comment]
@rublev sorry for a much too late reply, but if you're using Jest, you can configure [`moduleNameMapper`](https://github.com/facebook/jest/blob/master/docs/en/Configuration.md#modulenamemapper-objectstring-string). Otherwise you can use [ignore-styles](https://www.npmjs.com/package/ignore-styles) or something like that.

**Comment by imankit** [comment]
> new webpack.NormalModuleReplacementPlugin(//iconv-loader$/, 'node-noop')

Is the double slashh `//` before iconv-loader intended?
