### ISSUE TITLE
about auto detect charset

### ISSUE THREAD

**Issue by 6api** [andris9/encoding#19]
this is worked fine :
var b = encoding.convert(name, 'utf8', 'gbk');
console.log(b.toString());

this not worked:
var b = encoding.convert(name, 'utf8');
console.log(b.toString());

but i must know name is gbk, is any way to detect name charset?

**Comment by dchebakov** [comment]
For encoding auto-detection, you can use [jschardet](https://www.npmjs.com/package/jschardet) library. It works well both in the browser and NodeJs.
